### ISSUE TITLE
WHOIS on a nonexistent user does not send RPL_ENDOFWHOIS

### ISSUE THREAD

**Issue by slingamn** [Libera-Chat/sable#101]
I didn't reproduce this manually, but https://github.com/progval/irctest/pull/258 should be a repro case against Sable commit dcf8b53cac54f460b86861908d36d67969cf1eb2

<3

**Comment by spb** [comment]
Horse seems to say the current behaviour is OK:

> Servers MUST end their reply to WHOIS messages with one of these numerics:
>     [ERR_NOSUCHNICK](https://modern.ircdocs.horse/#errnosuchnick-401) (401)
>     [ERR_NOSUCHSERVER](https://modern.ircdocs.horse/#errnosuchserver-402) (402)
>     [ERR_NONICKNAMEGIVEN](https://modern.ircdocs.horse/#errnonicknamegiven-431) (431)
>     [RPL_ENDOFWHOIS](https://modern.ircdocs.horse/#rplendofwhois-318) (318)otherwise, even if they did not send any other numeric message. This allows clients to stop waiting for new numerics.

I can change it if this is going to cause problems, but I'm not seeing a reference to say the current setup is wrong.

**Comment by slingamn** [comment]
cc @progval who wrote this language AFAIK. Note that Horse says immediately above this:

>The server will answer this command with several numeric messages with information about the nicks, ending with [RPL_ENDOFWHOIS](https://modern.ircdocs.horse/#rplendofwhois-318).

so I think some emendation of the docs is probably required, whether it's to clarify that WHOIS responses MUST always end with 318 (the behavior of all tested ircds besides Sable), or to delete the "ending with RPL_ENDOFWHOIS" language quoted above.

**Comment by progval** [comment]
indeed, I don't know why I wrote that.

**Comment by spb** [comment]
Fixed in 0082a84
